name: Clang Format Checker
on: [push]
jobs:
  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RafikFarhad/clang-format-github-action@v4
        with:
          sources: "ef_lib/**/*.h,ef_lib/**/*.c,ef_lib/**/*.c"
