name: Test C++

on: [pull_request, push]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install system packages + get pytoch libs
        run: |
          sudo apt-get update
          sudo apt install cmake unzip zlib1g-dev build-essential libopencv-dev
          cd ef_lib
          wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-2.3.1%2Bcpu.zip
          unzip libtorch-cxx11-abi-shared-with-deps-2.3.1+cpu.zip

      - name: Build ef_lib
        run: |
          cd ef_lib
          cmake . -DCMAKE_PREFIX_PATH=./libtorch
          make -j

      - name: Run tests
        run: |
          cd ef_lib
          ./test
